### ISSUE TITLE
Replace "create_code" with "swap"

### ISSUE THREAD

**Issue by redirectme** [Veltas/zenv#17]
I noticed that "create_code" and "swap" are equivalent. 
`create_code:
	POP DE
	PUSH HL
	EX DE, HL
	JP next
...
swap:
	EX (SP), HL
	JP next

` 
So we can replace "CALL create_code" with "CALL swap", and delete the fragment create_code. Also, "DW create_code" should be replaced by "DW swap".

**Comment by Veltas** [comment]
Code reduction **and** you optimised SWAP as well, thanks!
Implemented in 7f7fc01 and 7393715.
