### ISSUE TITLE
Small bug in control.asm: wrong label "j:". It must be "_j:". 

### ISSUE THREAD

**Issue by redirectme** [Veltas/zenv#3]
Small bug in control.asm: wrong label "j:". It must be "_j:".

**Comment by Veltas** [comment]
Thanks! (How did you find this bug, by the way?) Fixed in 09b87e69f5

**Comment by redirectme** [comment]
First parameter of macro HEADER is ignored, label j: not used anywhere therefore this bug has no effect. I found it by reading the source.
