### ISSUE TITLE
Another register allocation

### ISSUE THREAD

**Issue by redirectme** [Veltas/zenv#5]
Why does the system have such a register allocation (HL as top, IY as PC, IX as RS counter)? 

[Brad Rodriguez. MOVING FORTH](https://bradrodriguez.com/papers/moving1.htm) recommends another register allocation for Z80.  For example, HL is used as a work register:

> HL is undoubtedly the most versatile register, and at one time or another it is tempting to use it for each of the Forth virtual registers. However, because of its versatility -- and because it is the only register which can be fetched byte-wise and used in an indirect jump -- HL should be used for W, Forth's all-purpose working register. (CASE STUDY 3: THE Z80) 

In the paper the choice of registers is explained. Maybe the another register allocation could be more optimal?

**Comment by Veltas** [comment]
MOVING FORTH is excellent and a must-read for anyone writing a Forth.

Another register allocation could be more optimal, I don't know.

I took most of Brad's advice, the TOS register and direct threading I used based on the article. Brad advised to try writing common words and see how efficient they were with your model.

For example, see fetch with my choice of registers:

```
	HEADER fetch, "@", 0
fetch:
	LD E, (HL)
	INC HL
	LD D, (HL)
	EX DE, HL
	JP next
```

Brad's choice of registers:

```
	HEADER fetch, "@", 0
fetch:
	LD L, C
	LD H, B
	LD C, (HL)
	INC HL
	LD B, (HL)
	JP next
```

As Brad says, HL is the most versatile register. And I think W or TOS are good candidates for HL. Brad chose W, I chose TOS. My decision was just what made sense to me, I am open to seeing a reimplementation with other register choices, or examples of other Z80 Forths that might be faster or more compact.

**Comment by redirectme** [comment]
OK, HL=W or HL=TOS  - they differ little in performance (speed and size) I agree. What about IY=IP?   Brad's choice is DE=IP (the advantage of DE: faster than IX\IY, no prefix IX\IY-command, swaping with HL).

**Comment by Veltas** [comment]
My logic is that it might as well be IY so I have more 'nice' registers to freely work with in normal words, to make up for a slower next routine. And also this is just what seemed easiest while playing around initially. I don't think it makes much difference performance-wise, but I'm happy to be corrected if you or someone has or writes a Forth with different choices.

If I wanted to make the transition as fast as possible I would use a subroutine threaded Forth. I consciously avoided this for space reasons, but maybe with intelligent use of inlining it wouldn't be so bad. Something to consider in future maybe.

**Comment by Veltas** [comment]
Also if you prefer, I have started an IRC channel on the OFTC network: #zenv.

**Comment by redirectme** [comment]
> Also if you prefer, I have started an IRC channel on the OFTC network: #zenv.
Thank you for the invitation but I'm afraid my English is not suitable for comfortable chating (unless you are ready to communicate in Russian).

**Comment by redirectme** [comment]
As far as I understand, you have HL =TOS and DE = W (it is convenient when the address is at the top, for example). If necessary,  EX DE, HL makes HL = W and DE = TOS temporarily (it is convenient for some other address). The length of this command is only 1 byte (and another byte for the reverse). Thus, at low cost, you have both allocations. I think this is a good choice.

**Comment by Veltas** [comment]
Closing as I don't plan on changing register allocation currently.
