### ISSUE TITLE
Remove "CALL colon_code" and "DX exit" from words that do not return control

### ISSUE THREAD

**Issue by redirectme** [Veltas/zenv#8]
Most high-level words have "CALL colon_code" and "DX exit" at the end. But there are words that do not return control. They are "WHAT?", "CWHAT?", "MAIN", "ABORT", "QUIT". They should not have "DX exit" at the bottom.  In addition, we need to replace "CALL colon_code"  with "CALL pop_pc_next" at the top of this words.

**Comment by Veltas** [comment]
I've removed the remaining `DX exit` (4301321) but I don't think there's enough utility/improvement to change from colon_code for such functions, just potential for confusion and issues with debugging or optimisation.
